import localFont from 'next/font/local';
import Header from './components/Layout/Header';
import Footer from './components/Layout/Footer';

import '../styles/main.scss';

const manrope = localFont({
	src: [
		{
			path: '../../public/fonts/Manrope-Regular.ttf',
			weight: '400',
			style: 'normal',
			fontFamily: 'manrope',
		},
		{
			path: '../../public/fonts/Manrope-Medium.ttf',
			weight: '500',
			fontFamily: 'manrope',
			style: 'normal',
		},
		{
			path: '../../public/fonts/Manrope-SemiBold.ttf',
			weight: '600',
			fontFamily: 'manrope',
			style: 'normal',
		},
		{
			path: '../../public/fonts/Manrope-Bold.ttf',
			weight: '700',
			fontFamily: 'manrope',
			style: 'normal',
		},
		{
			path: '../../public/fonts/Manrope-ExtraBold.ttf',
			weight: '800',
			fontFamily: 'manrope',
			style: 'normal',
		},
	],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={manrope.className}>
				<Header />
				<main id='content'>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
